version: 1.2.3+{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: mYjFV31UpA9DJblj4EH37NbPJ03Oci3yQAu210QeJMrlNdM/ayc8XJXnSr7wUKiR

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@4.2.6
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version

deploy:
  provider: GitHub
  auth_token:
    secure: mYjFV31UpA9DJblj4EH37NbPJ03Oci3yQAu210QeJMrlNdM/ayc8XJXnSr7wUKiR
  artifact: node_modules\font-manager\build\Release\fontmanager.node
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true

test: off

skip_non_tags: true
